
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ATRIBUICAO DIVIDE DO ELSE ENDIF ENDWHILE ID IF MAIS MENOS NUMERO PONTOEVIRGULA THEN VAR VEZES WHILEprograma : listadecomandoslistadecomandos : comando\n                      | listadecomandos comandocomando : VAR ID ATRIBUICAO expressao PONTOEVIRGULAcomando : ID ATRIBUICAO expressao PONTOEVIRGULA\n        expressao : expressao MAIS expressao\n    \n        expressao : expressao MENOS expressao\n    \n        expressao : expressao VEZES expressao\n    \n        expressao : expressao DIVIDE expressao\n    \n        expressao : ID\n    \n        expressao : NUMERO\n    \n        comando : IF expressao THEN listadecomandos ELSE listadecomandos ENDIF\n    \n        comando : WHILE expressao DO listadecomandos ENDWHILE\n    '
    
_lr_action_items = {'VAR':([0,2,3,8,17,22,24,25,30,31,32,33,34,35,],[4,4,-2,-3,4,4,-5,4,4,-4,4,-13,4,-12,]),'ID':([0,2,3,4,6,7,8,10,15,17,18,19,20,21,22,24,25,30,31,32,33,34,35,],[5,5,-2,9,12,12,-3,12,12,5,12,12,12,12,5,-5,5,5,-4,5,-13,5,-12,]),'IF':([0,2,3,8,17,22,24,25,30,31,32,33,34,35,],[6,6,-2,-3,6,6,-5,6,6,-4,6,-13,6,-12,]),'WHILE':([0,2,3,8,17,22,24,25,30,31,32,33,34,35,],[7,7,-2,-3,7,7,-5,7,7,-4,7,-13,7,-12,]),'$end':([1,2,3,8,24,31,33,35,],[0,-1,-2,-3,-5,-4,-13,-12,]),'ELSE':([3,8,24,25,31,33,35,],[-2,-3,-5,32,-4,-13,-12,]),'ENDWHILE':([3,8,24,30,31,33,35,],[-2,-3,-5,33,-4,-13,-12,]),'ENDIF':([3,8,24,31,33,34,35,],[-2,-3,-5,-4,-13,35,-12,]),'ATRIBUICAO':([5,9,],[10,15,]),'NUMERO':([6,7,10,15,18,19,20,21,],[13,13,13,13,13,13,13,13,]),'THEN':([11,12,13,26,27,28,29,],[17,-10,-11,-6,-7,-8,-9,]),'MAIS':([11,12,13,14,16,23,26,27,28,29,],[18,-10,-11,18,18,18,18,18,18,18,]),'MENOS':([11,12,13,14,16,23,26,27,28,29,],[19,-10,-11,19,19,19,19,19,19,19,]),'VEZES':([11,12,13,14,16,23,26,27,28,29,],[20,-10,-11,20,20,20,20,20,20,20,]),'DIVIDE':([11,12,13,14,16,23,26,27,28,29,],[21,-10,-11,21,21,21,21,21,21,21,]),'DO':([12,13,14,26,27,28,29,],[-10,-11,22,-6,-7,-8,-9,]),'PONTOEVIRGULA':([12,13,16,23,26,27,28,29,],[-10,-11,24,31,-6,-7,-8,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'listadecomandos':([0,17,22,32,],[2,25,30,34,]),'comando':([0,2,17,22,25,30,32,34,],[3,8,3,3,8,8,3,8,]),'expressao':([6,7,10,15,18,19,20,21,],[11,14,16,23,26,27,28,29,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> listadecomandos','programa',1,'p_programa','tempCodeRunnerFile.py',23),
  ('listadecomandos -> comando','listadecomandos',1,'p_listadecomandos','tempCodeRunnerFile.py',27),
  ('listadecomandos -> listadecomandos comando','listadecomandos',2,'p_listadecomandos','tempCodeRunnerFile.py',28),
  ('comando -> VAR ID ATRIBUICAO expressao PONTOEVIRGULA','comando',5,'p_comando_declaracaovariavel','tempCodeRunnerFile.py',35),
  ('comando -> ID ATRIBUICAO expressao PONTOEVIRGULA','comando',4,'p_comando_atribuicao','tempCodeRunnerFile.py',39),
  ('expressao -> expressao MAIS expressao','expressao',3,'p_expressao_soma','tempCodeRunnerFile.py',47),
  ('expressao -> expressao MENOS expressao','expressao',3,'p_expressao_menos','tempCodeRunnerFile.py',54),
  ('expressao -> expressao VEZES expressao','expressao',3,'p_expressao_vezes','tempCodeRunnerFile.py',61),
  ('expressao -> expressao DIVIDE expressao','expressao',3,'p_expressao_divisao','tempCodeRunnerFile.py',68),
  ('expressao -> ID','expressao',1,'p_expressao_id','tempCodeRunnerFile.py',75),
  ('expressao -> NUMERO','expressao',1,'p_expressao_numero','tempCodeRunnerFile.py',82),
  ('comando -> IF expressao THEN listadecomandos ELSE listadecomandos ENDIF','comando',7,'p_comando_if_then_else','tempCodeRunnerFile.py',89),
  ('comando -> WHILE expressao DO listadecomandos ENDWHILE','comando',5,'p_comando_while','tempCodeRunnerFile.py',96),
]
